[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# foundry.toml

solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 200
via_ir = true
ffi = true

[profile.ci]
verbosity = 4

[profile.test]
verbosity = 3
via_ir = true

[profile.dev]
via_ir = false